name: A workflow for the coursework
on: push

jobs:
  build:
    name: Coursework action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn compile
      - name: Run docker compose
        run: docker-compose up --abort-on-container-exit
